### ISSUE TITLE
Cambridge Learner Corpus(CLC) Corpus

### ISSUE THREAD

**Issue by MichaelCaohn** [chrisjbryant/doc-gec#1]
Hi authors, 

Thank you very much for this great work and for making this repository public. 

I have noticed that in your paper (Document-level grammatical error correction), you mentioned you have also used the Cambridge Learner Corpus (CLC) Corpus which contains around 2 Million parallel sentences during training (In Section 3.1). However, I failed to find a downloadable link for this corpus.

Would you mind sharing the link to download this CLC corpus?

**Comment by chrisjbryant** [comment]
Hi Michael,

Thank you for kind words. 
Unfortunately however, the CLC is a proprietary corpus so I'm afraid there is no public download link. Hopefully you can use an alternative data source in your experiments.

**Comment by MichaelCaohn** [comment]
I got it. Thank you very much :)
