### ISSUE TITLE
Regarding document-level and sentence-level training examples

### ISSUE THREAD

**Issue by shivmgg** [chrisjbryant/doc-gec#2]
Hey, 

Thanks for the work!

In your paper, you mentioned that you use sentence-level parallel data from CLC + FCE-train + W&I-train + NUCLE for pretraining, followed by CLC document-level parallel data for training and finally, in-domain document-level data from FCE-train + W&I-train + NUCLE for finetuning. May I know how did you extract these data subsets - sentence-level and document-level for CLC and other datasets? What do you mean by in-domain document-level data?

Regards,
Shivam Aggarwal

**Comment by chrisjbryant** [comment]
Hiya,

We used the full datasets in each stage so they were each effectively used twice in the final model. I.e. 
Sentence-level CLC, FCE, W&I, NUCLE for pretraining.
Document-level CLC for training (as created using  `json_to_doc_m2.py`).
Document-level FCE, W&I and NUCLE for finetuning (as created using  `json_to_doc_m2.py`).

In-domain just means the finetuning datasets are in the same domain as the test sets; i.e. W&I is the same domain as BEA-dev, FCE-test is the same domain as FCE-train, and NUCLE is the same domain as CoNLL-2014. All the fine-tuning datasets are combined to make them more generalisable across different test sets. 

Hope that helps!

**Comment by shivmgg** [comment]
Thanks a lot!

This is really helpful.
